# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='equipment_available',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='length',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='per_week',
        ),
        migrations.AlterField(
            model_name='profile',
            name='program_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_programs.Program'),
        ),
    ]
