# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exercise_priority', models.IntegerField(blank=True, default=0)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['exercise_priority'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('set_range', models.CharField(blank=True, max_length=255)),
                ('rep_range', models.CharField(blank=True, max_length=255)),
                ('percentage_range', models.CharField(blank=True, max_length=255)),
                ('rest_time', models.DurationField(blank=True, null=True)),
                ('exercise_limit', models.IntegerField(default=0)),
                ('type_priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ManyToManyField(related_name='associated_lifts', to='exercise_library.Type'),
        ),
    ]
