# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_library', '0002_auto_20170220_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.ManyToManyField(blank=True, related_name='associated_lifts', to='exercise_library.Type'),
        ),
    ]
