# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_library', '0003_auto_20170215_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
