# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_library', '0004_auto_20170220_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
