# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='main_muscle_group_targeted',
        ),
    ]
