# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
