# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['exercise', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('set_order', models.IntegerField(blank=True, default=0, null=True)),
                ('exercise_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_programs.ExerciseBlock')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_programs.Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('week_number', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_programs.Program')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_programs.MeasurementType'),
        ),
        migrations.AddField(
            model_name='exercisegroup',
            name='workout_group_belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assocated_exercise_groups', to='workout_programs.Workout'),
        ),
        migrations.AddField(
            model_name='exerciseblock',
            name='assigned_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_exercise_blocks', to='workout_programs.ExerciseGroup'),
        ),
        migrations.AddField(
            model_name='exerciseblock',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_library.Exercise'),
        ),
    ]
