# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_library', '0005_remove_exercise_main_muscle_group_targeted'),
        ('workout_programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('program', models.ManyToManyField(to='workout_programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_programs.Program')),
                ('week_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_programs.Week')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutProgram',
        ),
        migrations.AddField(
            model_name='exercisegroup',
            name='workout_group_belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assocated_exercise_groups', to='workout_programs.Workout'),
        ),
        migrations.AddField(
            model_name='exerciseblock',
            name='assigned_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_exercise_blocks', to='workout_programs.ExerciseGroup'),
        ),
        migrations.AddField(
            model_name='exerciseblock',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_library.Exercise'),
        ),
    ]
