# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0002_auto_20170218_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='program',
        ),
        migrations.AlterField(
            model_name='workout',
            name='week_number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
