# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0004_auto_20170220_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='measurement_ptr',
        ),
        migrations.DeleteModel(
            name='WorkTime',
        ),
    ]
