# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0005_auto_20170220_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='measurement',
        ),
        migrations.AddField(
            model_name='set',
            name='measurement',
            field=models.ManyToManyField(to='workout_programs.Measurement'),
        ),
    ]
