# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0006_auto_20170220_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='number',
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_to_be_completed', to='workout_programs.ExerciseBlock'),
        ),
    ]
