# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0007_auto_20170220_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='measurement_type',
        ),
        migrations.RemoveField(
            model_name='set',
            name='exercise_block',
        ),
        migrations.RemoveField(
            model_name='set',
            name='measurement',
        ),
        migrations.AddField(
            model_name='exerciseblock',
            name='prescription',
            field=models.TextField(default='no prescription has been written yet'),
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='MeasurementType',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
