# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0008_auto_20170307_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='tags',
        ),
    ]
