# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0009_auto_20170307_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(to='workout_programs.ProgramTag'),
        ),
    ]
