# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 03:47
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('workout_programs', '0011_auto_20170319_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programtag',
            name='related_programs',
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='ProgramTag',
        ),
    ]
