# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0012_auto_20170319_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='tags',
        ),
        migrations.AddField(
            model_name='program',
            name='experience_for',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='gender_for',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='goal_for',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='length_for',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='per_week_for',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='experience_for',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='gender_for',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='goal_for',
            field=models.CharField(default='', max_length=255),
        ),
    ]
