# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_label'),
        ('workout_programs', '0013_auto_20170323_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='experience_for',
        ),
        migrations.RemoveField(
            model_name='program',
            name='gender_for',
        ),
        migrations.RemoveField(
            model_name='program',
            name='goal_for',
        ),
        migrations.RemoveField(
            model_name='program',
            name='length_for',
        ),
        migrations.RemoveField(
            model_name='program',
            name='per_week_for',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='experience_for',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='gender_for',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='goal_for',
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(to='questions.Answer'),
        ),
        migrations.AddField(
            model_name='workout',
            name='tags',
            field=models.ManyToManyField(to='questions.Answer'),
        ),
    ]
