# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0014_auto_20170323_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(null=True, to='questions.Answer'),
        ),
    ]
