# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0015_auto_20170325_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['week_number', 'order']},
        ),
        migrations.RenameField(
            model_name='exercisegroup',
            old_name='workout_group_belongs_to',
            new_name='workout_in',
        ),
    ]
