# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('associated_lifts', models.ManyToManyField(related_name='muscles_used', to='exercise_library.Exercise')),
            ],
        ),
    ]
