# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_library', '0005_remove_exercise_main_muscle_group_targeted'),
        ('muscle_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='associated_lifts',
            field=models.ManyToManyField(related_name='muscles_used', to='exercise_library.Exercise'),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
